
#datasource configuration
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5441/${DB_NAME}
quarkus.datasource.username=${DB_USERNAME}
quarkus.datasource.password=${DB_PASSWORD}

#flyway
quarkus.flyway.migrate-at-start=true
quarkus.flyway.locations=db.migration

#hibernate
quarkus.hibernate-orm.sql-load-script=no-file

#CORS
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=http://localhost:5173, http://localhost:8080
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=Content-Type
quarkus.http.cors.access-control-allow-credentials=true

# jwt
mp.jwt.private-key.location=private.pem
mp.jwt.verify.publickey.location=public.pem
#mp.jwt.encrypt.key.location=public.pem
mp.jwt.verify.issuer=trip-app
quarkus.native.resources.includes=public.pem
mp.jwt.token.header=Cookie
mp.jwt.token.cookie=access_token

#mail
quarkus.mailer.auth-methods=DIGEST-MD5 CRAM-SHA256 CRAM-SHA1 CRAM-MD5 PLAIN LOGIN
quarkus.mailer.from=${GMAIL_EMAIL}
quarkus.mailer.host=smtp.gmail.com
quarkus.mailer.port=465
quarkus.mailer.tls=true
quarkus.mailer.username=${GMAIL_EMAIL}
quarkus.mailer.password=${GMAIL_PASSWORD}
quarkus.mailer.mock=false

frontend.url=http://localhost:5173

quarkus.live-reload.instrumentation=true

