quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5441/${DB_NAME}
quarkus.datasource.username=${DB_USERNAME}
quarkus.datasource.password=${DB_PASSWORD}

quarkus.flyway.migrate-at-start=true
quarkus.flyway.locations=db.migration
quarkus.hibernate-orm.sql-load-script=no-file

quarkus.http.cors.enabled=true
quarkus.http.cors.origins=http://localhost:5173, http://localhost:8080
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=Content-Type
#quarkus.http.cors.headers=Content-Type,Authorization
quarkus.http.cors.access-control-allow-credentials=true


#smallrye.jwt.sign.key.location = default location for sign() jwt
#smallrye.jwt.encrypt.key.location

mp.jwt.private-key.location=private.pem
mp.jwt.verify.publickey.location=public.pem
smallrye.jwt.encrypt.key.location=public.pem
mp.jwt.verify.issuer=trip-app
quarkus.native.resources.includes=public.pem
mp.jwt.token.header=Cookie
mp.jwt.token.cookie=access_token

#smallrye to MP.